name: "Keep Supabase Alive"

on:
  schedule:
    # Se ejecuta lunes, mi√©rcoles y viernes a las 00:00
    - cron: '0 0 * * 1,3,5'
  workflow_dispatch: 

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Database
        run: |
          curl -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/NOMBRE_DE_TU_TABLA?select=*" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
          -I